name: Build binary

on: [push, pull_request]

jobs:
  make_build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        golang: ['1.19.x', '1.20.x']
        arch: ['amd64', 'arm64']

      fail-fast: true

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.golang }}
          cache: true
          cache-dependency-path: go.sum

        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build and test with Make
        run: |
          make ci-build platform="${{ runner.os }}" arch="${{ matrix.arch }}"
          make test

      - name: Tar the artifacts
        run: tar -cvf ${{ format('bin/federator-{0}-{1}-{2}.tar', runner.os, matrix.arch, matrix.golang) }} ${{ format('bin/federator-{0}-{1}', runner.os, matrix.arch) }}

      - name: Upload artifacts for the functional tests workflow
        uses: actions/upload-artifact@v3
        with:
          name: ${{ format('federator-{0}-{1}-{2}', runner.os, matrix.arch, matrix.golang) }}
          path: ${{ format('bin/federator-{0}-{1}-{2}.tar', runner.os, matrix.arch, matrix.golang) }}
