name: Build binary

on: [push, pull_request]

jobs:
  make_build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        golang: [1.16, 1.17]

      fail-fast: true

    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build and test with Make
        run: |
          make ci-build platform="${{ runner.os }}"
          make test

      - name: Tar the artifacts
        run: tar -cvf ${{ format('bin/federator-{0}-{1}.tar', runner.os, matrix.golang) }} ${{ format('bin/federator-{0}', runner.os) }}

      - name: Upload artifacts for the functional tests workflow
        uses: actions/upload-artifact@v3
        with:
          name: ${{ format('federator-{0}-{1}', runner.os, matrix.golang) }}
          path: ${{ format('bin/federator-{0}-{1}.tar', runner.os, matrix.golang) }}
