name: Functional tests

on:
  workflow_run:
    workflows: ['Build binary']
    types:
      - completed

jobs:
  functional_tests:
    name: Run functional tests
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        golang: [1.16, 1.17]

      fail-fast: true

    steps:
      - name: Download artifacts from the build binary workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_binary.yml
          workflow_conclusion: success
          name: ${{ format('federator-{0}-{1}', runner.os, matrix.golang) }}
          path: bin/
          repo: ${{github.repository}}

      - name: Untar the artifacts and rename binary
        run: |
          tar -xvf ${{ format('bin/federator-{0}-{1}.tar', runner.os, matrix.golang) }}
          mv ${{ format('bin/federator-{0}', runner.os) }} bin/federator
          cd bin

      - name: Run "functional tests"
        run: |
          federator link --role-arn ${{ secrets.ASSUME_ROLE_ARN }}
          federator link --role-arn ${{ secrets.ASSUME_ROLE_ARN }} --region $ANOTHER_AWS_REGION
          federator link --role-arn ${{ secrets.ASSUME_ROLE_ARN }} --json
          federator creds --role-arn ${{ secrets.ASSUME_ROLE_ARN }}
          federator creds --role-arn ${{ secrets.ASSUME_ROLE_ARN }} --region $ANOTHER_AWS_REGION
          federator creds --role-arn ${{ secrets.ASSUME_ROLE_ARN }} --json
          federator trust-policy --arn arn:aws:iam::000000000000:user/myUser --external-id "test external id"
          federator trust-policy --arn arn:aws:iam::000000000000:user/myUser --external-id "test external id" --json
          federator trust-policy --account-id 000000000000 --external-id "test external id"
          federator trust-policy --account-id 000000000000 --external-id "test external id" --json
          federator --help
          federator --version
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'
          ANOTHER_AWS_REGION: 'us-east-2'
          CI_MODE: true

      - name: Rename for release
        run: |
          mv bin/federator ${{ format('bin/federator-{0}-{1}', runner.os, matrix.golang) }}

      - name: Upload artifacts for the draft release workflow
        uses: actions/upload-artifact@v2
        with:
          name: ${{ format('federator-{0}-{1}', runner.os, matrix.golang) }}
          path: ${{ format('bin/federator-{0}-{1}', runner.os, matrix.golang) }}
